DuAn/Areas/Admin/Controllers/CategoryAdminController.cs
using DuAn.IServices;
using DuAn.Models;
using DuAn.Services;
using Microsoft.AspNetCore.Mvc;

namespace DuAn.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryAdminController : Controller
    {
        private readonly ICategoryServices categoryServices;// Interface
        public CategoryAdminController()
        {
            categoryServices = new CategoryServices();
        }
        public IActionResult Index()
        {
            return View();
        }

        //show Category
        public ActionResult ShowAllCategory()
        {
            List<Category> categorys = categoryServices.GetAllCategorys();
            return View(categorys);
        }




        //thêm sửa xóa Color
        public IActionResult CreateCategory() // Hiển thị form
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(Category p)
        {
            if (categoryServices.CreateCategory(p))
            {
                return RedirectToAction("ShowAllCategory");
            }
            else return BadRequest();
        }

        public IActionResult DetailCategorys(Guid id)
        {
            var categorys = categoryServices.GetCategoryById(id);
            return View(categorys);
        }
        public IActionResult DeleteCategory(Guid id)
        {
            if (categoryServices.DeleteCategory(id))
            {
                return RedirectToAction("ShowAllCategory");
            }
            else return BadRequest();
        }
        [HttpGet]
        public IActionResult EditCategory(Guid id)
        {
            var categorys = categoryServices.GetCategoryById(id);
            return View(categorys);
        }
        public IActionResult EditCategory(Category p)
        {
            if (categoryServices.UpdateCategory(p))
            {
                return RedirectToAction("ShowAllCategory");
            }
            else return BadRequest();
        }
    }
}

DuAn/Areas/Admin/Views/CategoryAdmin/CreateCategory.cshtml
@model DuAn.Models.Category

@{
    ViewData["Title"] = "CreateCategory";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

   
<section class="content" >

    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> Thông Tin Thêm Mới Thể Loại</h3>

        </div>
        <div class="card-body"> 
            @using (Html.BeginForm("CreateCategory", "CategoryAdmin", FormMethod.Post))
            {
                  @Html.HiddenFor(p => p.Id)
                  <div class="bs-stepper-content">
                    <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">

                      <div class="form-group">
                        <label for="exampleInputEmail1">Name</label>
                           @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
                           @Html.ValidationMessageFor(Model => Model.Name, "", new { @class = "text-danger" })
                     
                      </div>

                      <div class="form-group">
                        <label for="exampleInputPassword1">Status</label>                    
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="Status" id="Status1" value="0" checked>
                            <label class="form-check-label" for="Status1">
                                Còn 
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="Status" id="Status2" value="1">
                            <label class="form-check-label" for="Status2">
                                Hết 
                            </label>
                        </div>
                      </div>
                      <div class="form-group">
                        <a href="/Admin/CategoryAdmin/ShowAllCategory" class="btn btn-primary" >Quay Lại</a>
                        <button type="Submit" class="btn btn-danger" >Submit</button>
                      </div>

                      
                    </div>
             
                  </div>
           
            }

        </div>


        <div class="card-footer"> 


        </div>

    </div>

</section>        
      
     

DuAn/Areas/Admin/Views/CategoryAdmin/DeleteCategory.cshtml
@model DuAn.Models.Category

@{
    ViewData["Title"] = "DeleteCategory";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    
}

<h1>DeleteCategory</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="DeleteCategory">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DuAn/Areas/Admin/Views/CategoryAdmin/DetailCategorys.cshtml
@model DuAn.Models.Category

@{
    ViewData["Title"] = "DetailCategorys";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>DetailCategorys</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
      @*  <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>*@
      @*  <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

DuAn/Areas/Admin/Views/CategoryAdmin/EditCategory.cshtml
@model DuAn.Models.Category

@{
    ViewData["Title"] = "EditCategory";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content" >

    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> Thông Tin Sửa Thể Loại</h3>

        </div>
        <div class="card-body"> 
            @using (Html.BeginForm("EditCategory", "CategoryAdmin", FormMethod.Post))
            {
                  @Html.HiddenFor(p => p.Id)
                  <div class="bs-stepper-content">
                    <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">

                      <div class="form-group">
                        <label for="exampleInputEmail1">Name</label>
                           @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
                           @Html.ValidationMessageFor(Model => Model.Name, "", new { @class = "text-danger" })
                     
                      </div>

                      <div class="form-group">
                        <label for="exampleInputPassword1">Trạng Thái</label>                    
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="Status" id="Status1" value="0" checked
                            @(Model.Status == 0 ? "checked" : "")>
                            <label class="form-check-label" for="Status1">
                                Còn 
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="Status" id="Status2" value="1"
                            @(Model.Status == 1 ? "checked" : "")>
                            <label class="form-check-label" for="Status2">
                                Hết 
                            </label>
                        </div>
                      </div>
                      <div class="form-group">
                        <a href="/Admin/CategoryAdmin/ShowAllCategory" class="btn btn-primary" >Quay Lại</a>
                        <button type="Submit" class="btn btn-danger" >Submit</button>
                      </div>

                      
                    </div>
             
                  </div>
           
            }

        </div>


        <div class="card-footer"> 


        </div>

    </div>

</section> 

DuAn/Areas/Admin/Views/CategoryAdmin/ShowAllCategory.cshtml
@model IEnumerable<DuAn.Models.Category>

@{
    ViewData["Title"] = "ShowAllCategoryAdmin";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content" >

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Quản Lý Thể Loại</h3>
            <div class="d-flex justify-content-end">

            <a href="@Url.Action("CreateCategory","CategoryAdmin")" > 
            <button type="button" class="btn btn-primary" style="text-align:right">
            <i class="bi bi-pencil-square"> Thêm</i>
            </button>
            </a>

            </div>
        
        </div>
        <div class="card-body">
            
<table class="table">
    <thead>
        <tr>
           @* <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
          @*  <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                 @if (item.Status == 0) {
                    <span>Còn </span>
                } else {
                    <span>Hết </span>
                }
              @*  @Html.DisplayFor(modelItem => item.Status)*@
            </td>
            <td>
                <a  class="btn btn-primary" href="@Url.Action("EditCategory","CategoryAdmin",new{id=item.Id})">Sửa</a>
                <a  class="btn btn-danger" href="@Url.Action("DetailCategorys","CategoryAdmin",new{id=item.Id})">Chi Tiết</a>
                <a  class="btn btn-warning" href="@Url.Action("DeleteCategory","CategoryAdmin",new{id=item.Id})">Xóa</a>
               
            </td>
        </tr>
}
    </tbody>
</table>

        </div>


        <div class="card-footer"> 

        </div>

    </div>

</section>