DuAn/Areas/Admin/Controllers/BillAdminController.cs
using DuAn.IServices;
using DuAn.Models;
using DuAn.Services;
using Microsoft.AspNetCore.Mvc;

namespace DuAn.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BillAdminController : Controller
    {
        public readonly IBillServices _billServices;
        public readonly IBillDetailsServices _billDetailsServices;
        public readonly IProductServices _productServices;
        public BillAdminController()
        {
            _billServices= new BillServices();
            _billDetailsServices = new BillDetailsServices();
            _productServices= new ProductServices();
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult ShowAllBill()
        {

            List<Bill> bills = _billServices.GetAllBills();
            return View(bills); // Truyền trực tiếp 1 Obj Model duy nhất sang View

        }


        public ActionResult ShowAllBillDetails(Guid idhd)
        {
                                  
            var listbillDetails = _billDetailsServices.GetBillDetailsByHB(idhd);
            var listbill = _billServices.GetAllBills();
            var listProduct = _productServices.GetAllProducts();

            ViewBag.listbillDetails = listbillDetails;
            ViewBag.listbill = listbill;
            ViewBag.listProduct = listProduct;


            return View();// Truyền trực tiếp 1 Obj Model duy nhất sang View

        }
    }
}

DuAn/Areas/Admin/Views/BillAdmin/ShowAllBill.cshtml
@model IEnumerable<DuAn.Models.Bill>

@{
    ViewData["Title"] = "ShowAllBill";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content" >

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Hóa Đơn</h3>

        </div>
        <div class="card-body"> 
<table class="table">
    <thead>
        <tr>
           @* <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sdt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diachi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
          @*  <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                        @{
                        DuAn.Models.ShopDbContext db = new DuAn.Models.ShopDbContext();
                        dynamic us = db.Users.Find(item.UserId);


                        if(us != null)
                        {
                            <spam>@us.Username</spam>
                        }
                    }
              @*  @Html.DisplayFor(modelItem => item.UserId)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sdt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diachi)
            </td>
            <td>
                  @if (item.Status == 0)
                  {
                       <span>Chờ Thanh toán</span>

                  }else if (item.Status == 1)
                  {
                       <span>Đã Thanh Toán</span>
                  }
                  else
                  {
                       <span>Đã Hủy</span>
                  }
                @*@Html.DisplayFor(modelItem => item.Status)*@
            </td>
            <td>
              <a  class="btn btn-warning" href="@Url.Action("ShowAllBillDetails","BillAdmin",new{idhd=item.Id})">HD CT</a>
            </td>
        </tr>
}
    </tbody>
</table>
        </div>


        <div class="card-footer"> 

        </div>

    </div>

</section>

DuAn/Areas/Admin/Views/BillAdmin/ShowAllBillDetails.cshtml
@using DuAn.Models;
@model IEnumerable<DuAn.Models.BillDetails>

@{
    ViewData["Title"] = "ShowAllBillDetails";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
       List<BillDetails> listbillDetails = ViewBag.listbillDetails;
     List<Product> listProduct = ViewBag.listProduct;
}


<section class="content" >

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Hóa Đơn CT</h3>

        </div>
        <div class="card-body"> 
<table class="table">
    <thead>
        <tr>
      @*     <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.IdSP)
            </th>
            <th>
                <span>ảnh</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHD)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in listbillDetails) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                      @{
                        DuAn.Models.ShopDbContext db = new DuAn.Models.ShopDbContext();
                        dynamic pro = db.Products.Find(item.IdSP);


                        if(pro != null)
                        {
                            <spam>@pro.Name</spam>
                        }
                    }
                @*@Html.DisplayFor(modelItem => item.IdSP)*@
            </td>
            <td>    
            @{
                 DuAn.Models.Product Products = db.Products.Find(item.IdSP);
            if (Products != null)
            {
                 <img src="@Products.LinkAnh" style="width: 100px; height: 100px;"/>
               
               
            }
            else
            {
                <span>Unknown</span>
            }
            }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td></td>
        </tr>
}
    </tbody>
</table>
        </div>


        <div class="card-footer"> 

        </div>

    </div>

</section>